- name: Login as Siebel and perform the following steps
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: add services 
      blockinfile:
       dest: "/opt/test"
       state: present
       insertafter: EOF
       create: yes
       content: |
        ------------------------------------------------------------------------------------------------------------------------------------------
        # .bashrc
        
        # Source global definitions
        if [ -f /etc/bashrc ]; then
        . /etc/bashrc
        fi

        # Uncomment the following line if you don't like systemctl's auto-paging feature:
        # export SYSTEMD_PAGER=

        # User specific aliases and functions

        JAVA_HOME=/opt/app/java/jdk1.8.0_241
        export JAVA_HOME
  
        export RESOLV_MULTI=off

        #export ORACLE_HOME=/opt/app/Oracle/product/12.2.0/client_1
        export ORACLE_HOME=/opt/app/Oracle/product/12.2.0/client_1

        export PATH=$PATH:$HOME/.local/bin:$HOME/bin:$ORACLE_HOME/bin:$JAVA_HOME/bin

        export LD_LIBRARY_PATH=$ORACLE_HOME/lib

        ------------------------------------------------------------------------------------------------------------------------------------------



